vector_map:
  raster_map_params:
    px_per_m: 2
    map_size_px: 100
    offset_frac_xy:
    - -0.75
    - 0.0
agent_type_defaults:
  only_predict:
  - VEHICLE
  - PEDESTRIAN
  no_types:
  - UNKNOWN
attention_radius:
  default: 20.0
  pairs:
    PEDESTRIAN:
      PEDESTRIAN: 10.0
      VEHICLE: 20.0
    VEHICLE:
      PEDESTRIAN: 20.0
      VEHICLE: 30.0
